# Generated by Django 2.2 on 2020-12-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='teacher',
        ),
        migrations.AddField(
            model_name='profile',
            name='userstatus',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
