# Generated by Django 2.2 on 2020-12-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_auto_20201229_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
