# Generated by Django 2.2 on 2020-12-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_remove_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
