# Generated by Django 2.2 on 2020-12-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_notes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
