# Generated by Django 2.2 on 2020-12-29 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_auto_20201229_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 6, 57, 20, 130614, tzinfo=utc)),
        ),
    ]
