# Generated by Django 2.2 on 2020-12-29 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_auto_20201229_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
