# Generated by Django 2.2 on 2020-12-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_auto_20201229_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
