# Generated by Django 2.2 on 2021-01-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0017_auto_20210102_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={},
        ),
    ]
