# Generated by Django 2.2 on 2021-01-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0019_auto_20210102_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
