# Generated by Django 2.2 on 2021-01-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0020_auto_20210103_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='dp.jpg', upload_to='media'),
        ),
    ]
